const paises = [
  ['1', 'US', 'Estados Unidos'],
  ['52', 'MX', 'Mexico'],
  ['53', 'CU', 'Cuba'],
  ['54', 'AR', 'Argentina'],
  ['55', 'BR', 'Brasil'],
  ['56', 'CL', 'Chile'],
  ['57', 'CO', 'Colombia'],
  ['58', 'VE', 'Venezuela'],
  ['51', 'PE', 'Peru'],
  ['591', 'BO', 'Bolivia'],
  ['593', 'EC', 'Ecuador'],
  ['595', 'PY', 'Paraguay'],
  ['598', 'UY', 'Uruguay'],
  ['502', 'GT', 'Guatemala'],
  ['503', 'SV', 'El Salvador'],
  ['504', 'HN', 'Honduras'],
  ['505', 'NI', 'Nicaragua'],
  ['506', 'CR', 'Costa Rica'],
  ['507', 'PA', 'Panama'],
  ['509', 'HT', 'Haiti'],
  ['1809', 'DO', 'Republica Dominicana'],
  ['1829', 'DO', 'Republica Dominicana'],
  ['1849', 'DO', 'Republica Dominicana'],
  ['1787', 'PR', 'Puerto Rico'],
  ['34', 'ES', 'Espana'],
  ['351', 'PT', 'Portugal'],
  ['33', 'FR', 'Francia'],
  ['39', 'IT', 'Italia'],
  ['49', 'DE', 'Alemania'],
  ['44', 'GB', 'Reino Unido'],
  ['31', 'NL', 'Paises Bajos'],
  ['32', 'BE', 'Belgica'],
  ['41', 'CH', 'Suiza'],
  ['30', 'GR', 'Grecia'],
  ['48', 'PL', 'Polonia'],
  ['40', 'RO', 'Rumania'],
  ['7', 'RU', 'Rusia'],
  ['380', 'UA', 'Ucrania'],
  ['90', 'TR', 'Turquia'],
  ['212', 'MA', 'Marruecos'],
  ['213', 'DZ', 'Argelia'],
  ['216', 'TN', 'Tunez'],
  ['218', 'LY', 'Libia'],
  ['20', 'EG', 'Egipto'],
  ['966', 'SA', 'Arabia Saudita'],
  ['971', 'AE', 'Emiratos Arabes'],
  ['970', 'PS', 'Palestina'],
  ['972', 'IL', 'Israel'],
  ['962', 'JO', 'Jordania'],
  ['961', 'LB', 'Libano'],
  ['963', 'SY', 'Siria'],
  ['964', 'IQ', 'Irak'],
  ['965', 'KW', 'Kuwait'],
  ['968', 'OM', 'Oman'],
  ['967', 'YE', 'Yemen'],
  ['974', 'QA', 'Qatar'],
  ['973', 'BH', 'Bahrein'],
  ['98', 'IR', 'Iran'],
  ['92', 'PK', 'Pakistan'],
  ['91', 'IN', 'India'],
  ['880', 'BD', 'Banglades'],
  ['93', 'AF', 'Afganistan'],
  ['234', 'NG', 'Nigeria'],
  ['233', 'GH', 'Ghana'],
  ['254', 'KE', 'Kenia'],
  ['256', 'UG', 'Uganda'],
  ['251', 'ET', 'Etiopia'],
  ['27', 'ZA', 'Sudafrica'],
  ['225', 'CI', 'Costa de Marfil'],
  ['221', 'SN', 'Senegal'],
  ['237', 'CM', 'Camerun'],
  ['62', 'ID', 'Indonesia'],
  ['60', 'MY', 'Malasia'],
  ['63', 'PH', 'Filipinas'],
  ['66', 'TH', 'Tailandia'],
  ['84', 'VN', 'Vietnam'],
  ['86', 'CN', 'China'],
  ['81', 'JP', 'Japon'],
  ['82', 'KR', 'Corea del Sur'],
  ['61', 'AU', 'Australia']
]

const orden = paises.slice().sort((a, b) => b[0].length - a[0].length)

const bandera = iso => iso
  .toUpperCase()
  .replace(/./g, c => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))

export function paisDesdeNumero(numero) {
  const digitos = String(numero || '').replace(/\D/g, '')
  const match = orden.find(([code]) => digitos.startsWith(code))
  if (!match) return { nombre: 'Desconocido', bandera: '🌍' }
  return { nombre: match[2], bandera: bandera(match[1]) }
}
